---
# Log in and run the commands specified in the group_vars/ files.
- name: ENSURE EPG IS ASSOCIATED TO CONTRACTS
  aci_epg_to_contract:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    ap: "{{ ap }}"
    epg: "{{ item.epg }}"
    contract: "{{ item.contract }}"
    contract_type: "{{ item.contract_type }}"
  with_items: "{{ epg_contracts }}"
  tags: epg
