---
# Log in and run the commands specified in the group_vars/ files.
- name: ENSURE FILTERS HAVE FILTER ENTRIES
  cisco.aci.aci_filter_entry:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    filter: "{{ item.filter }}"
    entry: "{{ item.entry }}"
    ether_type: "{{ item.ether_type }}"
    ip_protocol: "{{ item.protocol }}"
    dst_port_start: "{{ item.port }}"
    dst_port_end: "{{ item.port }}"
  with_items: "{{ filters }}"
  tags: filter, contract