---
# Log in and run the commands specified in the group_vars/ files.
- name: ENSURE APPLICATION EPGS EXISTS
  aci_epg:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    ap: "{{ ap }}"
    epg: "{{ item.epg }}"
    bd: "{{ item.bd }}"
    description: "EPG Created Using Ansible"
  with_items: "{{ epgs }}"
  tags: epg

