---
# Log in and run the commands specified in the group_vars/ files.
- name: ENSURE CONTRACTS SUBJECTS ARE ASSOCIATED WITH FILTERS
  aci_contract_subject_to_filter:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    contract: "{{ item.contract }}"
    subject: "{{ item.subject }}"
    filter: "{{ item.filter }}"
  with_items: "{{ contracts }}"
  tags: contract