---
# Log in and run the commands specified in the group_vars/ files.
- name: Creating contracts
  cisco.aci.aci_contract:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    contract: "{{ item.contract }}"
    scope: "context"
    description: "Contract Created Using Ansible"
  with_items: "{{ contracts }}"
  tags: contract