---
# Log in and run the commands specified in the group_vars/ files.
- name: Creating Tenant
  cisco.aci.aci_tenant:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    description: "Tenant Created Using Ansible"
  tags: tenant, vrf, bd, filter, contract, app, epg